install:
  - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-daily
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-meta-full

script:
  - cd QtQuick
  - qmake -project
  - pwd
  - qmake QtQuick.pro
  - make
