install:
  - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install libqt4-dev
  - sudo apt-get install -qq qt-components-ubuntu

script:
  - cd QtQuick
  - qmake -project
  - pwd
  - qmake QtQuick.pro
  - make
