install:
  - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-meta-full

script:
  - cd QtQuick
  - qmake -project
  - qmake qtquick.pro
  - make
