install:
  - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtcreator qt5-default

script:
  - cd QtQuick
  - qmake -project
  - pwd
  - qmake QtQuick.pro
  - make
