install:
  - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtcreator qt5-default qtdeclarative5-dev qtdeclarative5-qtquick2-plugin

script:
  - cd QtHtmlTest
  - qmake -project
  - pwd
  - qmake QtHtmlTest.pro
  - make
